feat: refactor Docker setup and database initialization scripts; remove unused scripts and improve CSV handling

diff --git a/.github/workflows/build-and-push-image.yml b/.github/workflows/build-and-push-image.yml
--- a/.github/workflows/build-and-push-image.yml
+++ b/.github/workflows/build-and-push-image.yml
@@ -1,4 +1,4 @@
-name: Build and Push Docker Image
+name: Build and Push ImageS
 
 on:
   workflow_call:
@@ -11,60 +11,49 @@ jobs:
   build:
     runs-on: ubuntu-latest
     env:
-      GITHUB_CI: true
       NEXUS_URL: ${{ secrets.NEXUS_URL }}
+      NEXUS_DOCKER_URL: ${{ secrets.NEXUS_DOCKER_URL }}
       NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
       NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-      DOCKER_DATA_MODEL_CONTAINER_NAME: infocompanies-data-model-postgres
+      DOCKER_DATA_MODEL_NAME: infocompanies-data-model-postgres
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.11"
-      
       - if: ${{ inputs.environment != 'prod' && inputs.environment != 'dev' }}
-        name: Makes sure inputs.environment is set
+        name: Validate environment input
         run: |
-          echo "Error: 'environment' input is required ('dev' or 'prod')."
+          echo "Error: 'environment' must be 'dev' or 'prod'."
           exit 1
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r ./requirements/build.in
-
-      - name: Copy template.env to .env
-        run: cp template.env .env
-
+      
       - if: ${{ inputs.environment == 'dev' }}
-        name: Run database setup script
-        run: ./db.sh
+        name: Login to Nexus native port for pulling CSVs
+        run: |
+          echo "${NEXUS_PASSWORD}" | docker login "${NEXUS_URL}" -u "${NEXUS_USERNAME}" --password-stdin
+          ./scripts/pull-csv.sh
+          docker logout "${NEXUS_URL}"
 
-      - name: Log in to Nexus Docker registry
-        run: echo "${NEXUS_PASSWORD}" | docker login "${NEXUS_URL}" -u "${NEXUS_USERNAME}" --password-stdin
-
-      - name: Generate a tag, commit and push the image to Nexus
+      - name: Build prefilled Postgres image
         run: |
           DOCKER_TAG=$(date +%Y%m%d%H%M%S)
-          IMAGE="${NEXUS_URL}/${DOCKER_DATA_MODEL_CONTAINER_NAME}-${{ inputs.environment }}:${DOCKER_TAG}"
 
-          if [ "${{ inputs.environment }}" = 'dev' ]; then
-            docker commit $DOCKER_DATA_MODEL_CONTAINER_NAME $IMAGE
+          if [ "${{ inputs.environment }}" == "dev" ]; then
+            DOCKERFILE="dev.Dockerfile"
           else
-            docker build -t $IMAGE -f prod.Dockerfile .
+            DOCKERFILE="prod.Dockerfile"
           fi
 
-          docker push $IMAGE
-          echo "Docker image pushed: $IMAGE"
+          IMAGE="${NEXUS_URL}/${DOCKER_DATA_MODEL_NAME}-${{ inputs.environment }}:${DOCKER_TAG}"
+          docker build -f "${DOCKERFILE}" -t $IMAGE .
 
-      - name: Remove Nexus login credentials
-        run: docker logout ${NEXUS_URL}
+          echo "${NEXUS_PASSWORD}" | docker login "${NEXUS_DOCKER_URL}" -u "${NEXUS_USERNAME}" --password-stdin
+          docker push $IMAGE
+          docker logout "${NEXUS_DOCKER_URL}"
+
 
       - name: Clean up Docker resources
         run: |
-          docker compose down || echo "No docker-compose file found or no containers running"
+          docker rm -f "${DOCKER_DATA_MODEL_NAME}" || true
+          docker volume rm pgdata || true
           docker system prune -f
-          echo "Cleaned up Docker resources."
